apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: some-service-tls
spec:
  secretName: some-service-tls
  issuerRef:
    name: external-issuer
    kind: Issuer
  dnsNames:
  - service.yourdomain.com